### ISSUE TITLE
Will Release 0.1.0 this month?

### ISSUE THREAD

**Issue by wuseal** [icerockdev/moko-widgets#197]
Hi, I expect to try your library in Project, And I want to know whether this library will release 0.1.0 in March. 😄

**Comment by Alex009** [comment]
hi, @wuseal ! 
i am still plan to release this month, but current dev-18 version is already very close to release API version. You can try lib already.

Before release i want do small cleanup internal code, add more support libs #167 #168 and more improve small api parts - #181 #152 

Also after release 0.1.0 in next releases can be small breaking changes too (i will try to do deprecations with "new way suggestions", but can't quarantee that there will be no breaking changes at all

**Comment by wuseal** [comment]
Clear! Very glad to hear the news, Thanks for making such excellent library for Kotlin Ecosystem.
Hope this library becomes more and more powerful.

**Comment by Alex009** [comment]
update: in march release not done :( 
part of work is done and already can be downloaded from dev repository - https://bintray.com/icerockdev/moko-dev/moko-widgets/2176e4b
but we should complete this tasks https://github.com/icerockdev/moko-widgets/milestone/15 and after small tests in our projects with this version of library we can deploy it as 0.1.0 release.

i think we need 1-2 weeks because now i have more priority issues

**Comment by wuseal** [comment]
Sure! 😄

**Comment by Alex009** [comment]
sad but project was frozen. now we update it to kotlin 1.5.20 and will release to mavenCentral. update done here #289
