### ISSUE TITLE
Error createContentWidget()

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#253]
Hi, I try parse in Screen using Coroutine, but createContentWidget() print error, I dont understand why, plz help.
My code:
![Снимок экрана 2020-06-25 в 15 50 44](https://user-images.githubusercontent.com/9552501/85724298-bf8e2880-b6fc-11ea-850d-1b126830ce11.png)
![Снимок экрана 2020-06-25 в 15 51 50](https://user-images.githubusercontent.com/9552501/85724316-c1f08280-b6fc-11ea-814c-c2f128b0d175.png)
![Снимок экрана 2020-06-25 в 15 52 50](https://user-images.githubusercontent.com/9552501/85724364-d16fcb80-b6fc-11ea-8424-633592b8a53c.png)

**Comment by Tetraquark** [comment]
Because the `createContentWidget` function must return an object of `Widget` class but you return object of `Job` class from `launch` function.

It is incorrect to run asynchronous coroutines inside the synchronous widget creation function `createContentWidget`. You send the request to the server that will send a response at an unspecified time. The screen will be rendered before the server sends a response. This is why widgets should observe data reactively something like this:

```kotlin
private val widgetData = MutableLiveData<String>("")

private fun launchAsyncRequest() {
    coroutineScope.launch {
        try {
            client.getStatusServer(url, "/endpoint", token) { response ->
                if (response.contains("success")) {
                    widgetData.value = response
                } else {
                    widgetData.value = "Error"
                }
            }
        } catch (exception: Exception) {
            widgetData.value = "Error"
        }
    }
}
    
override fun createContentWidget(): Widget<WidgetSize.Const<SizeSpec.AsParent, SizeSpec.AsParent>> {
    launchAsyncRequest()

    return with(theme) {
        container(size = WidgetSize.AsParent) {
            text(
                size = WidgetSize.WrapContent,
                text = widgetData.map { it.desc() }
            )
        }
    }
}
```

But it's bad way too. Do you use [moko-mvvm](https://github.com/icerockdev/moko-mvvm) library? A more correct way to run async code, launch all coroutines and send all requests to the server is to use `ViewModel` class. You can find the example of combined usage of moko-widgets and moko-mvvm [here](https://github.com/vevar/moko-widgets-education). Example of [screen](https://github.com/vevar/moko-widgets-education/blob/master/mpp-library/src/commonMain/kotlin/org/example/mpp/auth/InputCodeScreen.kt#L31) and [viewmodel](https://github.com/vevar/moko-widgets-education/blob/master/mpp-library/src/commonMain/kotlin/org/example/mpp/auth/InputCodeViewModel.kt#L10) for the screen.

**Comment by Diy2210** [comment]
Tnx!

**Comment by Diy2210** [comment]
I have one more question. I create Model from screen and create fun async. How call this fun in screen and get parse value.
My Model:
![Снимок экрана 2020-06-26 в 17 05 07](https://user-images.githubusercontent.com/9552501/85866191-b326d000-b7cf-11ea-910b-900be58d64f1.png)
My Screen code:
![Снимок экрана 2020-06-26 в 17 05 48](https://user-images.githubusercontent.com/9552501/85866207-ba4dde00-b7cf-11ea-91a7-40feeb24cb9a.png)

**Comment by Diy2210** [comment]
How use LiveData objects, else I use Model. 
My model data class:
![Снимок экрана 2020-06-30 в 14 01 13](https://user-images.githubusercontent.com/9552501/86120131-6a775b80-badc-11ea-870a-c71862c65564.png)

**Comment by Tetraquark** [comment]
Because you should change object in `value` property of the `MutableLiveData`, not the properties values of the object. So, change value of `LiveData` by creating new object oh the `HostModel` class:

```kotlin
data class HostModel(
    val hostName: String,
    val os: Int,
    val ip: String
)

val mutableLiveData = MutableLiveData<HostModel>(HostModel("Empty", 0, "0.0.0.0"))

fun launchAsyncRequest() {

    // ...
    
    mutableLiveData.value = MyDataClass(
        hostName = newHostName,
        os = newOs,
        ip = newIp
    )

    // ...
}
```

**Comment by Diy2210** [comment]
**Its work, thx again!**

**Comment by Diy2210** [comment]
Last question. How implement **MutableLiveData type Array(String)**?

**Comment by Tetraquark** [comment]
For array:
```kotlin
val stringArrayLiveData = MutableLiveData<Array<String>>(emptyArray())
stringArrayLiveData.value = arrayOf("1", "2", "3")
```

For list:
```kotlin
val stringListLiveData = MutableLiveData<List<String>>(emptyList())
stringListLiveData.value = listOf("1", "2", "3")
```

**Comment by Diy2210** [comment]
**Cool Tnx!**
